# Generated by Django 5.1.5 on 2025-01-24 13:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0002_alter_reservation_box_alter_reservation_id_etudiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_reservations', to='reservation.box')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
