# Generated by Django 5.1.4 on 2025-01-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
