# Generated by Django 5.1.5 on 2025-01-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
    ]
