# Generated by Django 5.1.5 on 2025-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.CharField(max_length=100)),
                ('box_type', models.CharField(choices=[('Small', 'Petit'), ('Large', 'Grand')], max_length=50)),
            ],
        ),
    ]
