# Generated by Django 5.1.1 on 2025-01-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='site',
        ),
    ]
