# Generated by Django 5.1.5 on 2025-01-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_boxreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='closing_time',
            field=models.TimeField(default='18:45'),
        ),
        migrations.AlterField(
            model_name='box',
            name='opening_time',
            field=models.TimeField(default='08:45'),
        ),
    ]
