# Generated by Django 5.1.5 on 2025-01-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
        ('reservation', '0003_alter_box_closing_time_alter_box_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant'),
        ),
    ]
