# Generated by Django 5.1.1 on 2025-01-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.AlterModelTable(
            name='etudiant',
            table='etudiant_etudiant',
        ),
    ]
