# Generated by Django 5.1.4 on 2025-01-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_alter_etudiant_options_alter_etudiant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salle', models.IntegerField()),
                ('places', models.IntegerField()),
                ('heure_debut', models.TimeField(default='08:30')),
                ('heure_fin', models.TimeField(default='20:30')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='etudiant.salle')),
            ],
        ),
    ]
