# Generated by Django 5.1.4 on 2025-01-09 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_salle_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='duree_creneau',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
